Homework #5 - Conditional operator If
vandervan/LEARN_JS pull request #6
Opened 2020-01-14 09:27 UTC by vandervan

Tasks from learn.javascript.ru

2020-01-14 15:06 UTC, Ventura27 requested changes

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +let name =  prompt("What's the 'оффициальное название' JavaScript?", '');
лишний пробел после знака равенства

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +if (name === 'ECMAScript'){
ставб пробел между ){

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +}else{
ставб пробелы до и после else

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +if (number > 0){
пробел между ){

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +} else if (number < 0){
пробел между ){

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +}else if (number = 0){
пробел между ){

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +(a + b) < 4 ? 'malo':'mnogo';
пробелы перед и после двоеточия

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +    (log === 'Сотрудник') ? 'Привет' :
Здесь лишние пробелы, строка должна начинаться без пробелов

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +                ''
в конце не хватает ";"

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> + */
В конце файла оставляй одну пустую строку

2020-01-14 15:06 UTC, Ventura27 commented on LEARN_JS_TASKS/If.js
> +    alert( 'Привет' );
лишние пробелы перед и после 'Привет'

2020-01-14 15:07 UTC, Ventura27 requested changes
Ты не делал задачи со второй ссылки?
https://learn.javascript.ru/switch

2020-01-15 22:01 UTC, vandervan commented
> Ты не делал задачи со второй ссылки?
> https://learn.javascript.ru/switch

Сделал задачи по Switch, добавлены коммитом в текущий pull request

2020-01-16 17:03 UTC, Ventura27 approved these changes

2020-01-16 17:26 UTC, merged